Feature/add helm chart unit tests
intershop/helm-charts pull request #138
Opened 2022-09-23 05:51 UTC by skiesewetter-intershop

## PR Type

[x] Build-related changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

Helm chart is checked with lint and integration tested trying an install but not unit tested.

## What Is the New Behavior?

Helm chart is checked with lint and integration tested trying an install and unit tested.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

2022-09-23 07:38 UTC, khauser requested changes
when we squash commit it into `develop/icm` the commit should start with `feat(icm): ...`

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +Each yaml file contains a test suite as defines by the [unittest]https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md#test-suite plugin.
"as defined" or better "is based on"

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +* `default-values_test.yaml` just checks if the chart can be renders using the checked in `values.yaml` (no custom values set).
"rendered" and "(with no custom values set)"

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +* there's a suite for each aspect (section) of the values
"of the `values.yaml`"

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +* there's a suite for all the _basic_  values (or value that are just passed through) named `basic-config-values_test.yaml`
whitespace after _basic_

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +    helm unittest --helm3 .
`helm unittest --helm3 .`

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +    helm plugin install https://github.com/quintush/helm-unittest
`helm plugin install https://github.com/quintush/helm-unittest`

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/values.yaml
>  # defined where the application shall run on
define

2022-09-23 07:38 UTC, khauser commented on charts/icm-as/tests/README.md
> +The files contained inside the same folder as this `README.md` contain test suite/case descriptors that can be executed using a helm plugin called [unittest](https://github.com/quintush/helm-unittest
"The files relative to this ``README.md`" would be much shorter.

2022-09-23 11:49 UTC, khauser requested changes
There are some comments...

2022-09-26 06:54 UTC, khauser submitted a review, later dismissed

2022-09-26 09:12 UTC, khauser approved these changes

2022-09-26 18:55 UTC, khauser submitted a review, later dismissed

2022-09-27 06:59 UTC, jometzner approved these changes

2022-09-27 07:02 UTC, stefanh1 approved these changes

2022-09-27 07:51 UTC, khauser requested changes

2022-09-27 07:51 UTC, khauser commented on charts/icm-as/templates/as-deployment.yaml
> -          command:
We still need this for the ISTE test execution. As far as I know there is no entrypoint field in k8s. So this command would overwrite the ENTRYPOINT in the Dockerfile.

2022-09-27 08:11 UTC, khauser commented on charts/icm-as/values.yaml
> -  command: |
If an `if`-condition would be used for the icm-as.image.command block this would be correct here.

2022-09-28 13:22 UTC, khauser approved these changes

2022-09-28 13:51 UTC, merged