fix: enable disable recreation (#201)
intershop/helm-charts pull request #202
Opened 2023-02-14 16:41 UTC by Thomas-Bergmann

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

The SQL Server database is created after restart.

Issue Number: Closes #201 

## What Is the New Behavior?

The SQL Server doesn't recreate the database per default.
An Option mssql.recreation allows to enable the previous behavior.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2023-02-16 06:20 UTC, skiesewetter-intershop requested changes

2023-02-16 06:20 UTC, skiesewetter-intershop commented on charts/icm-as/values.yaml
> +  # receate database on restart
TYPO: recreate

2023-03-01 06:38 UTC, skiesewetter-intershop submitted a review, later dismissed

2023-03-01 07:43 UTC, khauser approved these changes

2023-03-09 09:22 UTC, khauser submitted a review, later dismissed

2023-03-25 11:02 UTC, closed without merging