feat: add NewRelic Integration (#333)
intershop/helm-charts pull request #334
Opened 2023-06-26 12:02 UTC by Thomas-Bergmann

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Application / infrastructure changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

With ICM-AS 11.3.0 container provides New Relic integration of java agent. This new feature enable the activation of that feature via helm charts. Older versions of ICM-AS can use the new helm chart with deactivated feature.

Issue Number: Closes #333 

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

- [ ] Yes
- [x] No

## Other Information

2023-06-27 09:03 UTC, cortlepp-intershop commented on charts/icm-as/tests/newrelic_test.yaml
> +#data:
Why is this commented out? It seems like an important part of the test which should be checked.

2023-06-27 09:03 UTC, cortlepp-intershop commented on charts/icm-as/values.yaml
> +newrelic:
Maybe consider also adding this section to the `values.yaml` in the `icm` umbrella chart.

2023-06-28 08:48 UTC, Thomas-Bergmann commented on charts/icm-as/tests/newrelic_test.yaml
> +#data:
if you have a better idea to test a config map. please enhance the test.

2023-06-28 11:56 UTC, cortlepp-intershop commented on charts/icm-as/tests/newrelic_test.yaml
> +#data:
I added a test which checks for the presence of the license key in the data.

2023-06-29 05:14 UTC, skiesewetter-intershop requested changes

2023-06-29 05:14 UTC, skiesewetter-intershop commented on charts/icm-as/README.md
> -helm unittest --helm3  --output-file unit.xml --output-type JUnit charts/icm-as
Why did you change the output target and type?

2023-06-29 06:23 UTC, khauser approved these changes

2023-06-29 15:38 UTC, khauser submitted a review, later dismissed

2023-07-07 08:18 UTC, merged