feat(pwa): shared cache for nginx via memcached
intershop/helm-charts pull request #363
Opened 2023-08-03 13:06 UTC by dhhyi

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Application / infrastructure changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

- [ ] Yes
- [ ] No

## Other Information

2023-08-04 13:52 UTC, khauser requested changes
At the moment the core-team replaces the webadapter pagecaching with a **redis-cache**. Already for that reason you should also use redis as caching system because we shouln't use different systems here for maintenance effort. From my knowledge redis does also have better features than memcached.
Is it possible to switch here to redis, or do you have some doubts?
Apart from that (as I also told the Core-Team) it's not **best practice** to define a deployment on our own. It's better use existing deployments (helm charts). You will find one also for memcached and can include it as a dependency.

@Thomas-Bergmann: What do you think here? In my opinion the PWA should use **the same** redis cache as icm-as for maintenance and resource reasons. In the end you would have two redis clusters for big customers.. that doesn't make sence.

2023-08-04 13:52 UTC, khauser commented on charts/pwa/templates/deployment_memcached.yaml
> +          image: "memcached:latest"
Using latest is not best practice. Always try to use a specific version.

2023-09-10 09:54 UTC, Thomas-Bergmann commented
We discussed the options memcachd vs. redis, and the relations to the ICM. PWA is a separate application and it's not directly related to ICM. But for operational aspects, we decided to implement a "POC-" Redis connector too, so we can compare both solutions. If Redis matches the requirements, we will go with Redis. Additionally the cache invalidation must be part of the poc (and solution later).

2023-09-14 13:52 UTC, dhhyi commented
replaced by #401

2023-09-14 13:52 UTC, closed without merging