chore(icm): update certificate spc api version (#384)
intershop/helm-charts pull request #385
Opened 2023-08-17 08:52 UTC by cortlepp-intershop

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ x ] Application / infrastructure changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

Issue Number: Closes #384 

## What Is the New Behavior?

Update deprecated API.

## Does this PR Introduce a Breaking Change?

- [ x ] Yes
- [ ] No

## Other Information

2023-08-18 05:16 UTC, skiesewetter-intershop submitted a review, later dismissed

2023-08-18 05:55 UTC, Thomas-Bergmann commented
why is that a major break? since which k8s version the new version is supported?

2023-09-10 10:09 UTC, Thomas-Bergmann commented
Why is that PR mixed with the update strategy? please split.

2023-09-10 10:35 UTC, Thomas-Bergmann commented
it will break at least k8s 1.21.9. I could add an condition to support the older version.

2023-09-10 10:36 UTC, Thomas-Bergmann requested changes
please support both

2023-09-21 05:10 UTC, closed without merging