fix: can't enable job server without deploying controller (#448)
intershop/helm-charts pull request #449
Opened 2023-11-06 11:00 UTC by Thomas-Bergmann

* avoid deployment of controller in icm-as
* extract image/repository to values.yaml
* remove namespace icm-system from helm-template
* move environment variable declaration to _environments.tpl
* remove JOB server group from icm-as in case job server is enabled

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Application / infrastructure changes

## Release ##

Be sure to include PR label `major`, `minor` or `patch` when merging into `main`. This determines which part of the semantic version number needs to be bumped automatically.

## What Is the Current Behavior?

Issue Number: Closes #448 

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

- [ ] Yes
- [x] No

## Other Information

2023-11-06 14:34 UTC, khauser requested changes

2023-11-06 14:34 UTC, khauser commented on charts/icm-as/values.yaml
> +  # if enabled=true the job controller must be deployed at cluster separatelly. see icm-job chart.
separately

2023-11-09 14:00 UTC, skiesewetter-intershop approved these changes

2023-11-10 08:37 UTC, khauser approved these changes

2023-11-10 12:02 UTC, merged