feat(icm-web): Try to schedule WA pods evenly over different nodes
intershop/helm-charts pull request #729
Opened 2024-07-05 11:02 UTC by DevDavido

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [x] Application / infrastructure changes

## What Is the Current Behavior?

According to the default topology constraints a max. skew of 3 node hostnames regarding scheduled WA pods is possible.
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints

## What Is the New Behavior?

Configuration introduced to try to evenly schedule WA pods across different nodes.

Issue Number:
Fixes AB#97982

## Does this PR Introduce a Breaking Change?

- [ ] Yes
- [x] No

2024-07-05 13:50 UTC, khauser requested changes

2024-07-05 13:50 UTC, khauser commented on charts/icm-web/templates/wa-deployment.yaml
> +          # Chose schedulability over pod anti-affinity preference satisfaction
Choose

2024-07-05 13:50 UTC, khauser commented on charts/icm-web/values.yaml
> +  # define if the scheduler should try to place the replica set of WA pods evenly over different nodes
I would write replicatset

2024-07-05 13:51 UTC, Thomas-Bergmann approved these changes

2024-07-05 13:53 UTC, Thomas-Bergmann commented
It's a new functionality for the helm chart. not a bug.

2024-07-05 14:04 UTC, Thomas-Bergmann commented on charts/icm-web/templates/wa-deployment.yaml
> +          # Chose schedulability over pod anti-affinity preference satisfaction
```suggestion
          # Choose schedulability over pod anti-affinity preference satisfaction
```

2024-07-05 15:51 UTC, DevDavido commented on charts/icm-web/values.yaml
> +  # define if the scheduler should try to place the replica set of WA pods evenly over different nodes
Changed

2024-07-09 10:54 UTC, khauser approved these changes

2024-07-09 10:54 UTC, merged